libssh 0.9.6, krb5-1.18.4
ParallelSSH/ssh-python pull request #41
Opened 2022-01-14 10:57 UTC by enkore

0.9.6 does contain a fix for CVE-2021-3634 but this CVE is pretty low impact as setting one allowed KEX, like you'd generally prefer anyway, avoids it completely.

2022-01-28 14:45 UTC, enkore commented
rebased for CI fix

2022-02-03 13:59 UTC, pkittenis requested changes

2022-03-01 09:51 UTC, pkittenis commented
The new krb file converted to `.xz` is the only pending item here. I can resolve it based on this PR, or author can.

Thank you for the PR! Have also invited @enkore as a member to the organisation.

2022-03-02 15:02 UTC, enkore commented
Done - also, thanks!

2022-03-20 14:05 UTC, pkittenis commented
Merged with #44

2022-03-20 14:05 UTC, closed without merging